# Generated by Django 5.1 on 2026-06-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="outboxevent",
            index=models.Index(fields=["processed", "created_at"], name="outbox_pending_idx"),
        ),
    ]
