# Generated by Django 5.1 on 2026-06-09 21:55

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="api_keys",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "licensing_api_keys",
            },
        ),
        migrations.CreateModel(
            name="LicenseQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("max_api_calls", models.IntegerField(default=10000)),
                ("used_api_calls", models.IntegerField(default=0)),
                ("reset_at", models.DateTimeField()),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quota",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "licensing_quotas",
            },
        ),
    ]
