# Generated by Django 5.1 on 2026-06-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_remove_plan_fk"),
        ("licensing", "0002_daily_api_usage"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dailyapiusage",
            name="uq_daily_api_usage_customer_date",
        ),
        migrations.RenameIndex(
            model_name="dailyapiusage",
            new_name="licensing_d_custome_fa0444_idx",
            old_name="licensing_daily_api_customer_date_idx",
        ),
        migrations.AlterField(
            model_name="dailyapiusage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyapiusage",
            unique_together={("customer", "date")},
        ),
    ]
