# Generated by Django 5.0.14 on 2026-08-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0005_remove_plan_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Identificador estável usado no código (ex: new_dashboard_widget).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "enabled_globally",
                    models.BooleanField(
                        default=False,
                        help_text="Liga pra todo mundo — ignora a lista de customers abaixo.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enabled_customers",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Customers com a flag ligada individualmente (irrelevante se enabled_globally=True).",
                        related_name="enabled_flags",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "feature_flags",
                "ordering": ["key"],
            },
        ),
    ]
