# Generated by Django 5.1 on 2026-06-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="outbox_event_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("outbox_event_id__isnull", False)),
                fields=("outbox_event_id", "channel"),
                name="unique_notification_per_outbox_event_channel",
            ),
        ),
    ]
