# Generated by Django 5.0.14 on 2026-08-12 15:30

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import apps.blog.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "excerpt",
                    models.CharField(
                        help_text="Resumo curto — usado no card da listagem e como meta description padrão.",
                        max_length=300,
                    ),
                ),
                ("body", models.TextField(help_text="Corpo do post em Markdown.")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Convertida para WebP automaticamente.",
                        null=True,
                        upload_to=apps.blog.models._blog_cover_upload_path,
                    ),
                ),
                ("cover_image_alt", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Rascunho"), ("published", "Publicado")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=120)),
                ("meta_description", models.TextField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "blog_posts",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "published_at"], name="blog_posts_status_35de98_idx"
                    )
                ],
            },
        ),
    ]
