# Generated by Django 5.0.14 on 2026-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="Corpo do post em Markdown. Vazio ao criar — preenchido no editor completo.",
            ),
        ),
    ]
