# Generated by Django 5.0.14 on 2026-06-17 23:26

from django.db import migrations, models
import django.db.models.deletion

import apps.cms.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0003_alter_pricing_billing_cycle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceFeatureGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título do grupo")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Grupo de Funcionalidades",
                "verbose_name_plural": "Grupos de Funcionalidades",
                "db_table": "cms_service_feature_groups",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceFeatureItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("text", models.CharField(max_length=200, verbose_name="Item")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Ordem")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cms.servicefeaturegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Funcionalidade",
                "verbose_name_plural": "Itens de Funcionalidade",
                "db_table": "cms_service_feature_items",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        help_text="Substituirá o placeholder colorido. Convertida para WebP automaticamente.",
                        null=True,
                        upload_to=apps.cms.models._hero_upload_path,
                        verbose_name="Imagem hero (topo direito)",
                    ),
                ),
                (
                    "hero_image_alt",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt text da imagem hero"
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200, verbose_name="Tagline")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "meta_title",
                    models.CharField(blank=True, max_length=120, verbose_name="Meta title (SEO)"),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True, max_length=300, verbose_name="Meta description (SEO)"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cms_page",
                        to="products.product",
                        verbose_name="Produto / Serviço",
                    ),
                ),
            ],
            options={
                "verbose_name": "Página de Serviço",
                "verbose_name_plural": "Páginas de Serviço",
                "db_table": "cms_service_pages",
            },
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        help_text="Convertida para WebP automaticamente. Máx 1200px de largura.",
                        upload_to=apps.cms.models._gallery_upload_path,
                        verbose_name="Imagem",
                    ),
                ),
                ("alt", models.CharField(blank=True, max_length=200, verbose_name="Alt text")),
                ("caption", models.CharField(blank=True, max_length=300, verbose_name="Legenda")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Ordem")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="cms.servicepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da galeria",
                "verbose_name_plural": "Imagens da galeria",
                "db_table": "cms_service_images",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="servicefeaturegroup",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feature_groups",
                to="cms.servicepage",
            ),
        ),
        migrations.CreateModel(
            name="ServiceFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(max_length=300, verbose_name="Pergunta")),
                ("answer", models.TextField(verbose_name="Resposta")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Ordem")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="cms.servicepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "db_table": "cms_service_faqs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("riissen", "O que a Riissen entrega"),
                            ("client", "O que o cliente faz"),
                        ],
                        max_length=10,
                        verbose_name="Coluna",
                    ),
                ),
                ("text", models.CharField(max_length=300, verbose_name="Texto do item")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Ordem")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibilities",
                        to="cms.servicepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Responsabilidade",
                "verbose_name_plural": "Responsabilidades (Riissen / Cliente)",
                "db_table": "cms_service_responsibilities",
                "ordering": ["side", "order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.CharField(max_length=2, verbose_name='Número (ex: "01")')),
                ("title", models.CharField(max_length=100, verbose_name="Título do passo")),
                ("description", models.TextField(verbose_name="Descrição")),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Ordem")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="cms.servicepage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passo de implantação",
                "verbose_name_plural": "Passos de implantação",
                "db_table": "cms_service_steps",
                "ordering": ["order"],
            },
        ),
    ]
