# Generated by Django 5.1 on 2026-06-12 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_add_subscription_fk_to_invoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("asaas_event_id", models.CharField(db_index=True, max_length=100, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "billing_webhook_events",
            },
        ),
    ]
