# Generated by Django 5.1 on 2026-06-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_webhook_event_idempotency"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("subscription", "Assinatura"),
                    ("implementation", "Implantação"),
                    ("support", "Suporte"),
                ],
                db_index=True,
                default="subscription",
                max_length=20,
            ),
        ),
    ]
