# Generated by Django 5.1 on 2026-06-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_add_invoice_type_and_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="billing_type",
            field=models.CharField(
                choices=[
                    ("BOLETO", "Boleto"),
                    ("PIX", "Pix"),
                    ("CREDIT_CARD", "Cartão de crédito"),
                ],
                default="BOLETO",
                max_length=20,
            ),
        ),
    ]
