# Generated by Django 5.0.14 on 2026-06-10 00:58

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0003_phase4_soft_delete_invitations"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Ativo"),
                            ("grace_period", "Período de Tolerância"),
                            ("expired", "Expirado"),
                            ("cancelled", "Cancelado"),
                            ("suspended", "Suspenso"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="customers.customer",
                    ),
                ),
                (
                    "pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="products.pricing",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("grace_period", "Período de Tolerância"),
                            ("expired", "Expirado"),
                            ("suspended", "Suspenso"),
                            ("revoked", "Revogado"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licenses",
                        to="customers.customer",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="license",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "licenses",
            },
        ),
        migrations.CreateModel(
            name="ServiceAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("service_key", models.CharField(db_index=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisioning", "Provisionando"),
                            ("active", "Ativo"),
                            ("suspended", "Suspenso"),
                            ("failed", "Falhou"),
                            ("deprovisioned", "Desprovisionado"),
                        ],
                        db_index=True,
                        default="provisioning",
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=255, null=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("provisioned_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_accesses",
                        to="subscriptions.license",
                    ),
                ),
            ],
            options={
                "db_table": "service_accesses",
                "indexes": [
                    models.Index(
                        fields=["service_key", "status"], name="service_acc_service_490ea3_idx"
                    )
                ],
                "unique_together": {("license", "service_key")},
            },
        ),
    ]
