# Generated by Django 5.2.16 on 2026-08-11 06:22

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KeycloakClientIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("kc_uuid", models.CharField(max_length=64)),
                (
                    "realm",
                    models.CharField(
                        help_text="Denormalizado — sobrevive a uma troca de external_id.",
                        max_length=255,
                    ),
                ),
                ("app_name", models.CharField(max_length=255)),
                ("base_url", models.CharField(max_length=500)),
                ("redirect_uri", models.CharField(max_length=500)),
                ("language", models.CharField(max_length=20)),
                ("public_client", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_access",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keycloak_clients",
                        to="subscriptions.serviceaccess",
                    ),
                ),
            ],
            options={
                "db_table": "keycloak_client_integrations",
                "ordering": ["-created_at"],
                "unique_together": {("service_access", "client_id")},
            },
        ),
    ]
