# Generated by Django 5.1 on 2026-06-09 22:42
# plans app removed — plan FK was added here and dropped in 0005; dependency removed.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
