# Generated by Django 5.0.14 on 2026-06-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0003_phase4_soft_delete_invitations"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="asaas_customer_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
