# Generated by Django 5.1 on 2026-06-10 11:23
# No-op: plan FK was removed from 0002 when the plans app was dropped.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_add_asaas_customer_id"),
    ]

    operations = []
