# Generated by Django 5.0.14 on 2026-06-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricing",
            name="max_api_calls",
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name="pricing",
            name="max_users",
            field=models.IntegerField(default=5),
        ),
    ]
