# Generated by Django 5.0.14 on 2026-06-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_add_quota_limits_to_pricing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricing",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("monthly", "Mensal"),
                    ("annual", "Anual"),
                    ("lifetime", "Vitalício"),
                    ("one_time", "Cobrança Única"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="servicecomponent",
            name="service_key",
            field=models.CharField(
                choices=[
                    ("chatwoot", "Chatwoot"),
                    ("meta_whatsapp", "WhatsApp API Meta"),
                    ("n8n", "n8n Automação"),
                    ("glpi", "GLPI Helpdesk"),
                    ("zabbix", "Zabbix Monitoramento"),
                    ("proxmox", "Proxmox VE"),
                    ("truenas", "TrueNAS"),
                    ("nextcloud", "Nextcloud"),
                    ("aapanel", "AAPanel"),
                    ("evolution_api", "Evolution API"),
                ],
                max_length=50,
            ),
        ),
    ]
